# Generated by Django 6.0.2 on 2026-02-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_availavel',
            new_name='is_available',
        ),
    ]
