# Generated by Django 6.0.2 on 2026-02-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_is_availavel_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='perent',
            new_name='parent',
        ),
    ]
