# Generated by Django 6.0.2 on 2026-02-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogabout',
            options={'verbose_name': 'блог компании', 'verbose_name_plural': 'Блог компании'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'вопрос/ответ', 'verbose_name_plural': 'Вопросы/Ответы'},
        ),
        migrations.AlterModelOptions(
            name='plusabout',
            options={'verbose_name': 'плюс компании', 'verbose_name_plural': 'Плюсы компании'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
