# Generated by Django 6.0.2 on 2026-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание поста')),
                ('content', models.TextField()),
                ('published_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Блог пост',
                'verbose_name_plural': 'Блог посты',
                'ordering': ['-published_at'],
            },
        ),
    ]
